packages:
  - v0
  - v1
  - reduxstagram
  - conway
  - md-prevuer
  - bgcg
  - fyi
  - space-shooter
  - catch-of-the-day
  - stacker-news
  - v2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - ejs
  - es5-ext
  - esbuild
  - fsevents
  - gatsby
  - gatsby-cli
  - gatsby-telemetry
  - styled-components
  - yorkie
