packages:
  - v0
  - v1
  - reduxstagram
  - conway
  - md-prevuer
  - bgcg
  - fyi
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - ejs
  - es5-ext
  - esbuild
  - fsevents
  - styled-components
  - yorkie
