export const INITIAL_LINKS = [
  {
    description: "Conway's Game of Life: A Visualization in React",
    url: "https://conway.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },
  {
    description: "Ask HN: Do you remember what Instagram used to look like?",
    url: "https://reduxstagram.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },
  {
    description: "Unity Games in the Browser - Space Shooter",
    url: "https://space-shooter.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },

  {
    description: "Show HN: A Markdown Previewer in Vue",
    url: "https://md-prevuer.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },
  {
    description: "lgr.fyi: What used to be a URL shortener",
    url: "https://fyi.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },
  {
    description: "Show HN: Checkout this over-engineered fish website",
    url: "https://catch-of-the-day.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },
  {
    description: "Someone built a webpage for a Grilled Cheese Sandwich",
    url: "https://bgcg.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
      { user: { id: "10", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Ask HN: Do you the host the previous version of your website?",
    url: "https://v1.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
    ],
  },
  {
    description: "Show HN: The first version of my website",
    url: "https://v0.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
    ],
  },
  {
    description: "Show HN: I preserved the first webpage I ever made",
    url: "https://v0.leander.xyz/portfolio/tribute/",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
    ],
  },
  {
    description: "Ask HN: Anyone wanna play tic-tac-toe?",
    url: "https://v1.leander.xyz/projects/tictactoe",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description: "A version of 'Simon Says' with Vanilla JS",
    url: "https://v1.leander.xyz/projects/simon",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
    ],
  },
  {
    description:
      "New Study: Pomodoro Timers kinda work (probably, im not a scientist)",
    url: "https://v1.leander.xyz/projects/fuelgauge",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
    ],
  },
  {
    description: "freeCodeCamp has a passthrough for the Twitch.tv API",
    url: "https://v1.leander.xyz/projects/liveontwitch",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description: "Show HN: A local weather app in Vanilla JS",
    url: "https://v1.leander.xyz/projects/weather",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Ask HN: What's your favourite wikipedia wrapper? I'll go first.",
    url: "https://v1.leander.xyz/projects/wikiview",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Show HN: Sentry published a tool to facilitate building on their Integration Platform",
    url: "https://github.com/getsentry/integration-platform-example/",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description: "A minimal, colourful VS Code theme based on sentry.io",
    url: "https://marketplace.visualstudio.com/items?itemName=leeandher.unofficial-sentry-theme",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
    ],
  },
  {
    description: "Shutting down my minimal Twitter CLI",
    url: "https://github.com/leeandher/twitter-cl",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Show HN: For a capstone project, I built a MFA Infrared Vein Scanner",
    url: "https://www.youtube.com/watch?v=emK0LczlKes",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
    ],
  },
  {
    description: "I refactored a backend node project into a static site.",
    url: "https://delicious.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description: "Ask HN: Would you ever use a calculator in the browser?",
    url: "https://v1.leander.xyz/projects/calculator",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
    ],
  },
  {
    description: "A Quote Generator, styled after Tinder",
    url: "https://v1.leander.xyz/projects/quotes/",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
    ],
  },
  {
    description:
      "I published a web interface for my programming notes. They are out of date.",
    url: "https://leander.xyz/notes",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Show HN: For Sentry.io's 2022 HackWeek, I won with an organization scheme for issues",
    url: "https://youtu.be/iwiqmqWXU2o",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Show HN: For Sentry.io's 2023 HackWeek, I was runner-up with a templating scheme to make large notification changes",
    url: "https://youtu.be/E-W_qGKL3Bw",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description:
      "Show HN: For Sentry.io's 2024 HackWeek, I won by building in-app notifications",
    url: "https://youtu.be/dtChJsGHGiQ",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
    ],
  },
  {
    description: "Khan Academy Graduate: First time I ever used JavaScript",
    url: "https://v0.leander.xyz/portfolio/concentration/",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
      { user: { id: "8", name: "Anonymous" } },
      { user: { id: "9", name: "Anonymous" } },
    ],
  },
  {
    description: "Designing Explosion Graphics with Vanilla JS",
    url: "https://v0.leander.xyz/portfolio/inversion/",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
    ],
  },
  {
    description: "A winnable browser-game built by a high-schooler",
    url: "https://v0.leander.xyz/portfolio/rainbow/",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
      { user: { id: "4", name: "Anonymous" } },
      { user: { id: "5", name: "Anonymous" } },
      { user: { id: "6", name: "Anonymous" } },
      { user: { id: "7", name: "Anonymous" } },
    ],
  },
  {
    description: "Buying clothes online but they change price when you refresh",
    url: "https://sick-fits.leander.xyz",
    postedBy: { id: "1", name: "leander" },
    votes: [
      { user: { id: "2", name: "Anonymous" } },
      { user: { id: "3", name: "Anonymous" } },
    ],
  },
];
